/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.usjt.muzka;

import com.usjt.muzkaBD.MusicaDAO;
import com.usjt.muzkaBD.PreencherTabelaDAO;
import com.usjt.muzkaCod.Musica;
import com.usjt.muzkaCod.PreencheTabela;
import com.usjt.muzkaCod.Usuario;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;


/**
 *
 * @author steph
 */
public class AvaliarMusicas extends javax.swing.JFrame {
    Usuario usuario;
    
    /**
     * Creates new form AvaliarMusicas
     */
    public AvaliarMusicas() {
        super("Avalie as músicas");
        initComponents();
        preencheTabela(usuario);
        setLocationRelativeTo(null);
        buscarMusica();
        
    }
    public AvaliarMusicas(Usuario usuario) {
        super("Avalie as músicas");
        initComponents();
        preencheTabela(usuario);
        setLocationRelativeTo(null);
        this.usuario = usuario;
        setLocationRelativeTo(null);
        buscarMusica();
        //JOptionPane.showMessageDialog(null, usuario.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblVoltar = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAvaliar = new javax.swing.JTable();
        btnAvaliar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        cbxMusica = new javax.swing.JComboBox<>();
        cbxNota = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/setaEsquerda3.png"))); // NOI18N
        lblVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVoltarMouseClicked(evt);
            }
        });

        tblAvaliar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblAvaliar);

        btnAvaliar.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        btnAvaliar.setText("Avaliar");
        btnAvaliar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvaliarActionPerformed(evt);
            }
        });

        cbxMusica.setModel(new javax.swing.DefaultComboBoxModel<>(new Musica[] {}));
        cbxMusica.setBorder(null);
        cbxMusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxMusicaActionPerformed(evt);
            }
        });
        jScrollPane1.setViewportView(cbxMusica);

        cbxNota.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        cbxNota.setBorder(null);
        cbxNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxNotaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel1.setText("Nota");

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel2.setText("Músicas");

        jLabel5.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Avalie!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblVoltar)
                        .addGap(142, 142, 142)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(cbxNota, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(btnAvaliar, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVoltar)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAvaliar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVoltarMouseClicked
        // TODO add your handling code here:
        Dashboard dash = new Dashboard(usuario);
        dash.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblVoltarMouseClicked

    private void btnAvaliarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvaliarActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            avaliar();
            preencheTabela(usuario);
        } catch (Exception ex) {
            Logger.getLogger(AvaliarMusicas.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnAvaliarActionPerformed

    private void cbxMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxMusicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxMusicaActionPerformed

    private void cbxNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxNotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxNotaActionPerformed

    public void avaliar(){
        double posto;
        
        //cast para transformar a informação em um objeto do tipo música
        Musica musicaSelecionada = (Musica) cbxMusica.getSelectedItem();
        try{

            //pega a nota escolhida na combobox
            int nota = Integer.parseInt(cbxNota.getSelectedItem().toString());
            try{

                //chama a classe de BD 
                MusicaDAO musicadao = new MusicaDAO();

                //envia usuário e id da Música para verificar se ja foi avaliada
                //musicadao.verificaNota(usuario, musicaSelecionada);
                
                //verifica se usuário já atribuiu nota para a música
                if(musicadao.verificaNota(usuario, musicaSelecionada)){//caso sim, atualiza a nota na tabela NotaUsuarioMusica
                    musicadao.atualizarNota(usuario, musicaSelecionada, nota);
                    posto = musicadao.mediaPosto(musicaSelecionada); // média das notas dadas pra música
                    musicadao.atualizaPosto(musicaSelecionada, posto); //insere a informação da média na tabela
                }
                else{//se não, insere a nota na tabela NotaUsuarioMusica
                    musicadao.inserirNota(usuario, musicaSelecionada, nota);
                    posto = musicadao.mediaPosto(musicaSelecionada);// média das notas dadas pra música
                    musicadao.atualizaPosto(musicaSelecionada, posto);//insere a informação da média na tabela
            }}catch(Exception e){
                JOptionPane.showMessageDialog(null, "Erro ao avaliar a música");
                e.printStackTrace();
            }
            
        }catch(Exception e){
                    JOptionPane.showMessageDialog(null, "Erro ao pegar nota para avaliação");
                    e.printStackTrace();
                    this.initComponents();
                }
        
    }
   
    public void preencheTabela(Usuario usuario){
        
        PreencherTabelaDAO preencheTabela = new PreencherTabelaDAO();
        
        try {
            preencheTabela.preencherTabelaAvaliarMusica(usuario);
            ArrayList dados = new ArrayList();
            dados = preencheTabela.getDadosTabela();
            //JOptionPane.showMessageDialog(null, dados);
            
            String[] colunas = new String[]{"Musica", "Nota"};
            
            PreencheTabela modelo = new PreencheTabela(dados, colunas);
            tblAvaliar.setModel(modelo);
            
            tblAvaliar.getColumnModel().getColumn(0).setPreferredWidth(300);//tamanho da célula em largura
            tblAvaliar.getColumnModel().getColumn(0).setResizable(false);//se pode ou não ser redimensionável
            tblAvaliar.getColumnModel().getColumn(1).setPreferredWidth(74);
            tblAvaliar.getColumnModel().getColumn(1).setResizable(false);
            //tblAvaliar.getColumnModel().getColumn(1).setCellEditor(tce);
            tblAvaliar.getTableHeader().setReorderingAllowed(false);//não pode reordenar a tabela
            tblAvaliar.setAutoResizeMode(tblAvaliar.AUTO_RESIZE_OFF);//a tabela não pode ser redimensionada
            tblAvaliar.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
            
        } catch (Exception ex) {
            Logger.getLogger(AvaliarMusicas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void buscarMusica(){
        try {
            MusicaDAO musicadao = new MusicaDAO();
            Musica[] musicas = musicadao.obterMusica();
            cbxMusica.setModel(new DefaultComboBoxModel<>(musicas));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Musicas indisponíveis, tente novamente mais tarde.");
            e.printStackTrace();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AvaliarMusicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AvaliarMusicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AvaliarMusicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AvaliarMusicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AvaliarMusicas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvaliar;
    private javax.swing.JComboBox<Musica> cbxMusica;
    private javax.swing.JComboBox<String> cbxNota;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblVoltar;
    private javax.swing.JTable tblAvaliar;
    // End of variables declaration//GEN-END:variables
}
