/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.usjt.muzka;
    
import com.usjt.muzkaBD.GeneroDAO;
import com.usjt.muzkaBD.PreencherTabelaDAO;
import com.usjt.muzkaBD.UsuarioGeneroDAO;
import com.usjt.muzkaCod.Usuario;
import com.usjt.muzkaCod.Genero;
import com.usjt.muzkaCod.PreencheTabela;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;


/**
 *
 * @author steph
 */
public class GenerosFavoritos extends javax.swing.JFrame {
        Usuario usuario;
    /**
     * Creates new form GenerosPreferidos
     */
    public GenerosFavoritos() {
        super("Meus gêneros preferidos");
        initComponents();
        setLocationRelativeTo(null);
        preencheTabela(usuario);
        buscarGenero();
    }
    
    public GenerosFavoritos(Usuario usuario) {
        super("Meus gêneros preferidos");
        initComponents();
        this.usuario = usuario;
        setLocationRelativeTo(null);
        preencheTabela(usuario);
        buscarGenero();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGenero = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        cbxGenero = new javax.swing.JComboBox<>();
        btnAdicionarGenero = new javax.swing.JButton();
        btnExcluirGenero = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/setaEsquerda3.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        tblGenero.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblGenero);

        cbxGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxGeneroActionPerformed(evt);
            }
        });
        jScrollPane2.setViewportView(cbxGenero);

        btnAdicionarGenero.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        btnAdicionarGenero.setText("Adicionar Genero");
        btnAdicionarGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarGeneroActionPerformed(evt);
            }
        });

        btnExcluirGenero.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        btnExcluirGenero.setText("Excluir Gênero");
        btnExcluirGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirGeneroActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Gêneros favoritos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(60, 60, 60)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAdicionarGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnExcluirGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(19, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionarGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluirGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        
        //envidando o objeto usuário para a nova tela
        Dashboard dash = new Dashboard(usuario);
        dash.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void btnAdicionarGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarGeneroActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            adicionarGenero();
            preencheTabela(usuario);
        } catch (Exception ex) {
            Logger.getLogger(AvaliarMusicas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAdicionarGeneroActionPerformed

    private void cbxGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxGeneroActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cbxGeneroActionPerformed

    private void btnExcluirGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirGeneroActionPerformed
        // TODO add your handling code here:
        excluirGenero();
        preencheTabela(usuario);
    }//GEN-LAST:event_btnExcluirGeneroActionPerformed

    //preencher a combobox
    public void buscarGenero(){
        try {
            GeneroDAO generodao = new GeneroDAO();
            Genero[] generos = generodao.obterGenero();
            cbxGenero.setModel(new DefaultComboBoxModel<>(generos));
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gêneros indisponíveis, tente novamente mais tarde.");
            e.printStackTrace();
        }
    }
    
    public void adicionarGenero(){
        // pegando um objeto e tranformando para o tipo gênero
        Genero generoSelecionado = (Genero) cbxGenero.getSelectedItem();
        
        //int idGenero = generoSelecionado.getId();
        try{
            UsuarioGeneroDAO ugenerodao = new UsuarioGeneroDAO();
            //verifica se o gênero já foi inserido na tabela
            if(ugenerodao.existeGeneroPreferido(usuario, generoSelecionado)){
                JOptionPane.showMessageDialog(null, "O gênero " + generoSelecionado.getNome() 
                        +" já está adicionado em sua lista de favoritos");
            }else
                //insere novo gênero na lista
                ugenerodao.inserirGeneroPreferido(usuario,generoSelecionado);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Problemas técnicos. Tentenovamente mais tarde");
            e.printStackTrace();
        }
    }
    
//exclui gênero preferido do usuário da tabela de gêneros preferidos
    public void excluirGenero(){
        
        GeneroDAO generodao = new GeneroDAO();
        UsuarioGeneroDAO ugenerodao = new UsuarioGeneroDAO();
        
        //pega a linha que foi selecionada na tabela
        int linhaSel = tblGenero.getSelectedRow();
        
        //pega o gênero da linha selecionada
        String generos = tblGenero.getValueAt(linhaSel,0).toString();
        
        //pega o id do gênero selecionado na tabela
        int id = generodao.consultaId(generos);
        //envia um objeto genero e um objeto usuario para o BD
        ugenerodao.excluirGeneroPreferido(id, usuario);        
    }
    
    //preenche a tabela de gêneros preferidos
    public void preencheTabela(Usuario usuario){
        
        PreencherTabelaDAO preencheTabela = new PreencherTabelaDAO();
        
        try {
            preencheTabela.preencherTabelaGeneroPreferido(usuario);
            ArrayList dados = new ArrayList();
            //pega o número de linhas referente a quantos gêneros têm na consulta
            dados = preencheTabela.getDadosTabela();
            //JOptionPane.showMessageDialog(null, dados);
            
            //define o nome das colunas e a quantidade
            String[] colunas = new String[]{"Gênero", "Data inserção"};
            
            PreencheTabela modelo = new PreencheTabela(dados, colunas);
            tblGenero.setModel(modelo);//pega o modelo de tabela
            
            tblGenero.getColumnModel().getColumn(0).setPreferredWidth(200);//tamanho da célula em largura
            tblGenero.getColumnModel().getColumn(0).setResizable(false);//se pode ou não ser redimensionável
            tblGenero.getColumnModel().getColumn(1).setPreferredWidth(120);
            tblGenero.getColumnModel().getColumn(1).setResizable(false);
            tblGenero.getTableHeader().setReorderingAllowed(false);//pode reordenar a tabela
            tblGenero.setAutoResizeMode(tblGenero.AUTO_RESIZE_OFF);//a tabela não pode ser redimensionada
            tblGenero.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);//só pode selecionar uma linha da tabela
        } catch (Exception ex) {
            Logger.getLogger(AvaliarMusicas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GenerosFavoritos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GenerosFavoritos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GenerosFavoritos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GenerosFavoritos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GenerosFavoritos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarGenero;
    private javax.swing.JButton btnExcluirGenero;
    private javax.swing.JComboBox<Genero> cbxGenero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblGenero;
    // End of variables declaration//GEN-END:variables
}
